// Shared helpers for the four budget pages.
const B=(()=>{
const $=id=>document.getElementById(id);
// allocate N squares to items by largest remainder
function alloc(items,N=100){const tot=items.reduce((a,x)=>a+x[1],0)||1;const c=items.map(([k,v])=>{const e=v/tot*N;return [k,Math.floor(e),e%1];});const used=c.reduce((a,x)=>a+x[1],0);c.slice().sort((a,b)=>b[2]-a[2]).slice(0,N-used).forEach(x=>x[1]++);return c;}
function grid(id,n=100){const w=$(id);w.innerHTML='';const out=[];for(let i=0;i<n;i++){const c=document.createElement('i');c.dataset.i=i;c.style.transitionDelay=(i*3)+'ms';w.appendChild(c);out.push(c);}return out;}
const EMB=new URLSearchParams(location.search).get('embed')==='1';
const Y0=(()=>{const m=location.hash.match(/y=(\d{4})/);return m?+m[1]:2025;})();
const K0=(()=>{const m=location.hash.match(/k=([a-z_]+)/);return m?m[1]:null;})();
// keep the year (and an open line) in the address, and keep embed mode when moving between parts
function carry(y,k){const h='#y='+y;document.querySelectorAll('.nav a,.tile').forEach(a=>{a.href=a.getAttribute('href').split('#')[0].split('?')[0]+(EMB?'?embed=1':'')+h;});try{history.replaceState(null,'',location.pathname+location.search+h+(k?'&k='+k:''));}catch(e){}}
function embed(id){if(!EMB)return;document.body.classList.add('embed');const el=()=>document.querySelector('.card');let last=0;const ph=()=>{const c=el();if(!c||innerWidth<50)return;const h=Math.ceil(c.getBoundingClientRect().height);if(h>0&&h!==last){last=h;[id,'nyc-budget-explainer'].forEach(i=>parent.postMessage({type:'vc-embed-height',id:i,height:h},'*'));}};addEventListener('load',ph);addEventListener('resize',ph);let n=0;const t=setInterval(()=>{ph();if(++n>20)clearInterval(t);},300);addEventListener('load',()=>{if(window.ResizeObserver&&el())new ResizeObserver(ph).observe(el());});}
// n shades of one colour, dark to light (or reversed)
function ramp(v,n,o={}){const a=o.light?-0.5:-0.3,b=o.light?0.25:0.5,out=[];for(let i=0;i<n;i++){let t=n===1?0.3:i/(n-1);if(o.reverse)t=1-t;const w=a+(b-a)*t;out.push(w<0?`color-mix(in srgb, var(${v}) ${Math.round((1+w)*100)}%, #050507)`:`color-mix(in srgb, var(${v}) ${Math.round((1-w)*100)}%, #fff)`);}return out;}
// trend line, always from zero
function spark(o){const ys=o.ys,v=o.vals;const W=Math.max(220,Math.round(o.width||300)),H=60,L=2,R=o.right||44,T=8,Bm=16;const hi=o.max||Math.max(5,Math.ceil(Math.max(...v)/5)*5);const X=i=>L+i/(ys.length-1)*(W-L-R),Y=x=>T+(1-x/hi)*(H-T-Bm);const path=v.map((x,i)=>(i?'L':'M')+X(i).toFixed(1)+','+Y(x).toFixed(1)).join(' ');const ci=Math.max(0,ys.indexOf(o.cur));const aud=o.aud||ys.length;const solid=(X(aud-1)-L).toFixed(0);const f='font-family="halyard-text,sans-serif"';const fmt=o.fmt||(x=>'$'+x.toFixed(0));
 return `<svg class="spark" style="${o.show?'display:block':''}" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-label="Trend from ${ys[0]} to ${ys[ys.length-1]}, axis from zero"><line x1="${L}" x2="${W-R}" y1="${Y(0)}" y2="${Y(0)}" stroke="#dddddd"/><path d="${path}" fill="none" stroke="${o.color}" stroke-width="2" stroke-dasharray="${solid} 999"/>${aud<ys.length?`<path d="${path}" fill="none" stroke="${o.color}" stroke-width="2" stroke-dasharray="0 ${solid} 3 3"/>`:''}<circle cx="${X(ci)}" cy="${Y(v[ci])}" r="3.5" fill="#050507"/><text x="${W-R+6}" y="${Y(v[ci])+4}" font-size="12" ${f} fill="#050507">${fmt(v[ci])}</text><text x="${L}" y="${H-3}" font-size="10" fill="#707175" ${f}>${ys[0]}</text><text x="${W-R}" y="${H-3}" text-anchor="end" font-size="10" fill="#707175" ${f}>${ys[ys.length-1]}</text></svg>`;}
// names written on the big blocks of a 10-column waffle
function labels(wafId,sq,blocks,on){const w=$(wafId);w.querySelectorAll('.lbl').forEach(e=>e.remove());if(!on||!sq.length)return;const unit=sq[0].offsetWidth+3;if(!unit||Math.round((w.clientWidth+3)/unit)!==10)return;
 blocks.forEach(b=>{if(b.n<3)return;let s=b.start,avail=Math.min(b.n,10-(s%10));if(avail<3){const rest=b.n-avail;if(rest<3)return;s+=avail;avail=Math.min(rest,10);}const wpx=avail*unit-3;if(b.text.length*6.3+12>wpx)return;const e=sq[s],l=document.createElement('span');l.className='lbl'+(b.dark?' dk':'');l.textContent=b.text;l.style.left=e.offsetLeft+'px';l.style.top=e.offsetTop+'px';l.style.maxWidth=wpx+'px';if(b.color)l.style.background=b.color;w.appendChild(l);});}
// click and keyboard activation, delegated
function act(el,sel,fn){el.addEventListener('click',e=>{const r=e.target.closest(sel);if(r&&el.contains(r))fn(r,e);});el.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const r=e.target.closest(sel);if(r&&el.contains(r)){e.preventDefault();fn(r,e);}});}
function mini(id,items){const el=$(id);if(el)el.innerHTML=alloc(items).map(([c,n])=>`<i style="background:${c}"></i>`.repeat(n)).join('');}
function player(o){let timer=null;const stop=()=>{if(timer){clearInterval(timer);timer=null;o.btn.textContent='Play';}};
 o.btn.addEventListener('click',()=>{if(timer){stop();return;}const ys=o.years();let i=o.cur()>=ys[ys.length-1]?0:ys.indexOf(o.cur());o.btn.textContent='Pause';o.draw(ys[i]);timer=setInterval(()=>{i++;if(i>=ys.length){stop();return;}o.draw(ys[i]);},o.ms||600);});
 o.range.addEventListener('input',e=>{stop();o.draw(+e.target.value);});return {stop};}
function tipper(waf,tip,html){waf.addEventListener('mousemove',e=>{const t=e.target.closest('i');const h=t&&html(t);if(!h){tip.style.display='none';return;}tip.style.display='block';tip.style.left=Math.min(e.clientX+12,innerWidth-232)+'px';tip.style.top=(e.clientY+14)+'px';tip.innerHTML=h;});waf.addEventListener('mouseleave',()=>tip.style.display='none');}
function peek(keyEl,sq,active){keyEl.addEventListener('mouseover',e=>{const r=e.target.closest('.row');if(!r||active())return;sq().forEach(q=>q.classList.toggle('peek',q.dataset.k!==r.dataset.k));});keyEl.addEventListener('mouseleave',()=>sq().forEach(q=>q.classList.remove('peek')));}
const REV={property_tax:'#ff7c53',personal_income_tax:'#217ebe',sales_tax:'#dde44c',business_taxes:'#e7466d',other_taxes:'#cea9be',state_aid:'#394882',federal_aid:'#9b9fbc',fees_fines_other:'#707175'};
const SPE={education:'#217ebe',social_services:'#e7466d',public_safety:'#394882',pensions:'#ff7c53',benefits:'#cea9be',debt_service:'#050507',health:'#dde44c',general_government:'#9b9fbc',environmental:'#707175',everything_else:'#c9c9cb'};
return {$,alloc,grid,Y0,K0,EMB,carry,embed,ramp,spark,labels,act,mini,player,tipper,peek,REV,SPE};})();
